### ISSUE TITLE
Tablet view does not really fit

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/thinktecture-hacks#10]
iPad in Chrome Device View

![image](https://cloud.githubusercontent.com/assets/888718/17586903/e23626e6-5fc4-11e6-8daa-25456e96ac3d.png)

The right margin there...

And space seems somehow wasted, at first sight.

**Comment by kaeku** [comment]
I'm not really sure if we even need the live view on mobile devices. My best guess is that one would want as much editing space as possible. 
Should we drop the live preview on mobile?

**Comment by ChristianWeyer** [comment]
Yes, good idea for tablet view.

**Comment by kaeku** [comment]
solved in b9e89a4
