### ISSUE TITLE
Event details form on tablet somehow looks... deserted ;-)

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/thinktecture-hacks#23]
Like this:

![image](https://cloud.githubusercontent.com/assets/888718/17636187/fc43a4ec-60db-11e6-8288-33aadb4f7902.png)

**Comment by kaeku** [comment]
This is due to the input field's max-width being somewhere around 300px and most probably flexbox being buggy in Safari (again). 👎

**Comment by SteffenJahr** [comment]
![image](https://cloud.githubusercontent.com/assets/7164777/18413922/4a95632c-77b8-11e6-97fe-683f93ed4edd.png)

I have updated the form so it will show the desktop arrangement of the fields. Should be enough. Maybe we have to redesign it later.
